server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: forum-demo
  jackson:
    time-zone: Asia/Shanghai
  datasource:
    url: jdbc:mysql://mysql:3306/blog
    username: blog_app
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000
